{% set name = "django-browser-reload" %}
{% set version = "1.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-browser-reload-{{ version }}.tar.gz
  sha256: 3f9ce1578d23b9ab6af4bf3c9a4416cfea4c9af9e8aca81e0973157a76588285

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - django >=2.2
    - python >=3.7
    - python-tzdata

test:
  imports:
    - django_browser_reload
    - django_browser_reload.templatetags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/django-browser-reload
  summary: Automatically reload your browser in development.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
