{% set name = "django-browser-reload" %}
{% set version = "1.12.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 875b6bd01db13380522ccb4ae75871a2edeae74bb5ac92bf32eb76763d575d86

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - django >=3.2
    - python >=3.8
    - python-tzdata

test:
  imports:
    - django_browser_reload
    - django_browser_reload.templatetags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/django-browser-reload
  summary: Automatically reload your browser in development.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
