{% set name = "django-browser-reload" %}
{% set version = "1.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4384cccd49580b4d60f3266166462912b771e55e510fdb1a945270862209b799

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - django >=3.2
    - python >=3.7
    - python-tzdata

test:
  imports:
    - django_browser_reload
    - django_browser_reload.templatetags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/django-browser-reload
  summary: Automatically reload your browser in development.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
