{% set name = "django-browser-reload" %}
{% set version = "1.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4e3507c10518f4c7439588aaed2f0c21b503878ecea7b18893f1e635e0cbe3ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - django >=3.2
    - python >=3.8
    - python-tzdata

test:
  imports:
    - django_browser_reload
    - django_browser_reload.templatetags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/django-browser-reload
  summary: Automatically reload your browser in development.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
