{% set name = "django-browser-reload" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-browser-reload-{{ version }}.tar.gz
  sha256: aae28aa1af8ac85ae257d260a84bef6e78f2132a5c0a99ed05099ec2e7a794bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django >=2.2
    - python >=3.6
    - python-tzdata

test:
  imports:
    - django_browser_reload
    - django_browser_reload.templatetags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/django-browser-reload
  summary: Automatically reload your browser in development.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
