schema_version: 1

context:
  name: django-browser-reload
  version: "1.20.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: a5e23fc4d0ab67d594edf220fb1e3fd8b35fad4c36b9a03b590bf84f58549735

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=77
  run:
    - python >=${{ python_min }}
    - asgiref >=3.6
    - django >=4.2

tests:
  - python:
      imports:
        - django_browser_reload
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Automatically reload your browser in development.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/adamchainz/django-browser-reload

extra:
  recipe-maintainers:
    - thewchan
